// ── Daily Briefing 예제 — 베이지+블랙 테마 ──
// 사용법: typst compile daily-briefing.typ daily-briefing.pdf

#set document(title: "Daily Briefing Example", author: "Your Name")
#set page(
  paper: "a4",
  margin: (x: 2cm, y: 2cm),
  fill: rgb("#FDF6EC"),
  header: context {
    if counter(page).get().first() > 1 {
      set text(size: 8pt, fill: rgb("#8B7355"))
      grid(columns: (1fr, 1fr),
        [Daily Briefing],
        align(right)[2026.04.14],
      )
      v(-3pt)
      line(length: 100%, stroke: 0.5pt + rgb("#D4C5A9"))
    }
  },
  footer: context {
    set text(size: 8pt, fill: rgb("#8B7355"))
    align(center)[#counter(page).display("1 / 1", both: true)]
  },
)

#set text(font: ("Pretendard", "Noto Sans KR", "NanumGothic"), size: 10pt, lang: "ko", fill: rgb("#1A1A1A"))
#set heading(numbering: none)
#set par(justify: true, leading: 0.75em)

// ── 색상 팔레트: 베이지 + 블랙 ──
#let card-bg = rgb("#FFF8EE")
#let accent = rgb("#1A1A1A")
#let muted = rgb("#8B7355")
#let border = rgb("#D4C5A9")
#let highlight = rgb("#C8956C")
#let tag-bg = rgb("#EDDFCC")

// ── 유틸리티 ──
#let card(body, title: none) = {
  block(width: 100%, inset: 14pt, radius: 6pt,
    fill: card-bg, stroke: 0.5pt + border
  )[
    #if title != none [#text(weight: "bold", size: 11pt, fill: accent)[#title] #v(6pt)]
    #body
  ]
}

#let tag(label) = {
  box(inset: (x: 5pt, y: 2pt), radius: 3pt, fill: tag-bg
  )[#text(size: 7.5pt, weight: "bold", fill: muted)[#label]]
}

#show heading.where(level: 1): it => {
  v(0.6em)
  block(width: 100%, inset: (bottom: 4pt),
    stroke: (bottom: 2pt + accent)
  )[#text(size: 15pt, weight: "bold", fill: accent)[#it.body]]
  v(0.3em)
}

#show heading.where(level: 2): it => {
  v(0.4em)
  text(size: 11pt, weight: "bold", fill: highlight)[#it.body]
  v(0.15em)
}

// ═══ 타이틀 ═══
#v(1.5cm)
#align(center)[
  #text(size: 11pt, fill: muted, tracking: 2pt)[DAILY BRIEFING]
  #v(0.3em)
  #text(size: 28pt, weight: "bold", fill: accent)[2026. 04. 14]
  #v(0.2em)
  #text(size: 12pt, fill: muted)[화요일]
  #v(0.8em)
  #line(length: 25%, stroke: 1pt + accent)
  #v(0.8em)
  #block(width: 60%, inset: 10pt, radius: 4pt, fill: card-bg, stroke: 0.5pt + border)[
    #set text(size: 9pt, fill: muted)
    #align(center)[일정 *2건* · 이메일 *8건* · 캘린더 추천 *1건*]
  ]
]
#v(1cm)

// ═══ 오늘의 일정 ═══
= 오늘의 일정

#card(title: "10:00 — 11:00")[
  #grid(columns: (auto, 1fr), gutter: 10pt,
    [#tag("미팅")], [*팀 주간회의*],
    [], [장소: 대회의실],
    [], [상태: #text(fill: rgb("#27AE60"), weight: "bold")[확정]],
  )
]

#v(6pt)

#card(title: "14:00 — 15:00")[
  #grid(columns: (auto, 1fr), gutter: 10pt,
    [#tag("외부")], [*외부 커피챗*],
    [], [상태: #text(fill: rgb("#27AE60"), weight: "bold")[확정]],
  )
]

#v(6pt)

#block(width: 100%, inset: 10pt, radius: 4pt, fill: rgb("#F5ECD7"), stroke: (left: 3pt + highlight))[
  #text(size: 9pt, fill: muted)[오전 회의 → 점심 → 오후 커피챗. 이동 시간 여유 있음.]
]

#pagebreak()

// ═══ 이메일 요약 ═══
= 최근 24시간 이메일 (8건)

== 뉴스레터

#block(breakable: false)[
#card[
  #grid(columns: (auto, 1fr), gutter: 6pt,
    [#tag("AI")], [*이번 주 AI 핫토픽 정리* \ #text(size: 8.5pt, fill: muted)[주간 뉴스레터 · 4/14 07:30]],
    [], [],
    [#tag("Tech")], [*새로운 프레임워크가 등장했다* \ #text(size: 8.5pt, fill: muted)[기술 블로그 · 4/13 18:00]],
  )
]
]

== 네트워크

#block(breakable: false)[
#card[
  #grid(columns: (auto, 1fr), gutter: 8pt,
    [#tag("LinkedIn")], [*1촌 요청 2건* — IT/마케팅 분야 실무자],
  )
]
]

== 업무

#block(breakable: false)[
#card[
  #grid(columns: (auto, 1fr), gutter: 8pt,
    [#tag("일정")], [*프로젝트 마감일 리마인더*],
    [], [#text(size: 9pt, fill: muted)[이번 주 금요일까지 제출]],
  )
]
]

== 보안

#block(breakable: false)[
#card[
  #text(size: 9.5pt)[보안 알림 2건 — 모두 정상 #text(fill: rgb("#27AE60"))[OK]]
]
]

#pagebreak()

// ═══ 캘린더 추천 ═══
= 캘린더 등록 추천

#block(width: 100%, inset: 14pt, radius: 6pt, fill: rgb("#F5ECD7"), stroke: 1pt + highlight)[
  #text(weight: "bold", size: 12pt, fill: accent)[추천 1건]
  #v(8pt)
  #grid(columns: (auto, 1fr), gutter: 8pt,
    [*제목:*], [프로젝트 마감일],
    [*시간:*], [2026.04.18 (금) 종일],
    [*출처:*], [이메일 리마인더],
    [*충돌:*], [없음],
  )
  #v(8pt)
  #text(size: 9pt, fill: muted)[승인 시 Google Calendar에 자동 추가됩니다.]
]

// ═══ 하단 ═══
#v(2em)
#align(center)[
  #line(length: 20%, stroke: 0.5pt + border)
  #v(4pt)
  #text(size: 8pt, fill: muted)[Generated by typst-korean-report]
]
